name: movie_mind_app
description: A new Flutter project for MovieMind.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 网络请求
  dio: ^5.3.0
  # 图片缓存加载
  cached_network_image: ^3.3.0
  # 轮播图 (仿照首页 Banner)
  carousel_slider: ^5.0.0
  # 评分星星
  flutter_rating_bar: ^4.0.1
  # 图标
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true